export const GRANTS = [
  {
    title: 'Tony Elumelu Entrepreneurship Programme',
    amount: 'US$ 5,000 seed capital',
    amount_max: 5000,
    description:
      'Non-refundable seed capital plus business mentorship for African entrepreneurs. The largest entrepreneurship programme on the continent.',
    eligibility: 'African entrepreneur, 18+, with a business idea or early-stage venture. Apply through the TEFConnect portal when applications open.',
    deadline: 'Rolling',
    type: 'All sectors',
    region: 'Pan-Africa',
    source: 'Tony Elumelu Foundation',
    external_url: 'https://tefconnect.com/',
    image_url: null,
  },
  {
    title: 'Google for Startups Accelerator: Africa',
    amount: 'Equity-free support + funding access',
    amount_max: 50000,
    description:
      '10-week accelerator for African tech startups with equity-free support, mentorship, credits and access to Google-invested funding.',
    eligibility: 'Seed to Series-A tech and AI startups with HQ or meaningful operations in Africa.',
    deadline: 'Rolling',
    type: 'Tech / Innovation',
    region: 'Pan-Africa',
    source: 'Google',
    external_url: 'https://startup.google.com/programs/accelerator/africa/',
    image_url: null,
  },
  {
    title: 'Orange Corners',
    amount: 'US$ 5,000 + incubation',
    amount_max: 5000,
    description:
      'Incubation, market access and funding for young entrepreneurs across Africa and the Middle East, including Nigeria and Ghana through local partners.',
    eligibility: 'Young entrepreneurs (18–35) in participating countries, ready for incubation.',
    deadline: 'Rolling',
    type: 'Small business',
    region: 'Pan-Africa',
    source: 'Orange Corners',
    external_url: 'https://www.orangecorners.com/',
    image_url: null,
  },
  {
    title: 'Flat6Labs',
    amount: 'Seed + follow-on funding',
    amount_max: 300000,
    description:
      'One of the region\'s largest seed investors and accelerators, running cohorts with investment, mentoring and founder network.',
    eligibility: 'Early-stage founders with a validated product in MENA and Africa markets.',
    deadline: 'Rolling',
    type: 'Tech / Innovation',
    region: 'Pan-Africa',
    source: 'Flat6Labs',
    external_url: 'https://flat6labs.com/',
    image_url: null,
  },
  {
    title: 'Founders Factory Africa',
    amount: 'Investment + venture studio',
    amount_max: 150000,
    description:
      'Africa-focused venture studio and accelerator investing in tech founders solving real local problems.',
    eligibility: 'Tech founders with a digital product and proof of traction in Africa.',
    deadline: 'Rolling',
    type: 'Tech / Innovation',
    region: 'Pan-Africa',
    source: 'Founders Factory',
    external_url: 'https://foundersfactory.com/',
    image_url: null,
  },
  {
    title: 'Kiva Microloans',
    amount: 'Loans up to US$ 15,000',
    amount_max: 15000,
    description:
      'Crowdfunded, low-interest loans for small businesses in 70+ countries, funded by a community of lenders.',
    eligibility: 'Any business owner. Borrow through a Kiva field partner active in your country.',
    deadline: 'Rolling',
    type: 'Small business',
    region: 'Global',
    source: 'Kiva',
    external_url: 'https://www.kiva.org/',
    image_url: null,
  },
  {
    title: 'Africa No Filter – Story Grants',
    amount: 'US$ 4,000 – 8,000 micro-grants',
    amount_max: 8000,
    description:
      'Micro-grants for African creatives, storytellers and journalists telling nuanced, hopeful narratives about Africa.',
    eligibility: 'African creatives, storytellers and journalists. Calls open periodically for story grants.',
    deadline: 'Rolling',
    type: 'Creative',
    region: 'Pan-Africa',
    source: 'Africa No Filter',
    external_url: 'https://africanofilter.org/',
    image_url: null,
  },
  {
    title: 'GEA YouStart & SME Support (Ghana)',
    amount: 'GH₵ 5,000 – GH₵ 50,000',
    amount_max: 50000,
    description:
      'Government-backed SME support: YouStart starter packages, training and financing windows for young Ghanaian businesses.',
    eligibility: 'Registered Ghanaian MSMEs. YouStart targets entrepreneurs aged 18–40.',
    deadline: 'Rolling',
    type: 'Small business',
    region: 'Ghana',
    source: 'Ghana Enterprises Agency',
    external_url: 'https://gea.gov.gh/',
    image_url: null,
  },
  {
    title: 'Village Capital',
    amount: 'Equity-free investment US$ 50K – 150K',
    amount_max: 150000,
    description:
      'Venture fund investing in early-stage startups; the entrepreneur founders themselves vote on who receives the investment.',
    eligibility: 'Early-stage startups in agriculture, edtech, fintech and climate, per announced programme.',
    deadline: 'Rolling',
    type: 'All sectors',
    region: 'Pan-Africa',
    source: 'Village Capital',
    external_url: 'https://vilcap.com/',
    image_url: null,
  },
  {
    title: 'AFAWA – African Development Bank',
    amount: 'Financing programme',
    amount_max: 250000,
    description:
      'Affirmative Finance Action for Women in Africa: closes the gender financing gap by investing through partner banks in women-led business.',
    eligibility: 'Women-led or women-owned business in an AFAWA partner country, via partner financial institutions.',
    deadline: 'Rolling',
    type: 'Women-led',
    region: 'Pan-Africa',
    source: 'African Development Bank',
    external_url: 'https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/afawa',
    image_url: null,
  },
]

export const SAVING_CIRCLES = [
  { name: 'Ayah Susu Circle', amount: 'GH₵ 200 / week', period: 'weekly', total_members: 12, visibility: 'Private', status: 'active' },
  { name: 'Trader Women Group', amount: 'GH₵ 100 / week', period: 'weekly', total_members: 20, visibility: 'Public', status: 'active' },
  { name: 'Market Queens Co-op', amount: 'GH₵ 250 / week', period: 'bi-weekly', total_members: 10, visibility: 'Public', status: 'active' },
  { name: 'Pearl & Gold Traders', amount: 'GH₵ 150 / week', period: 'weekly', total_members: 15, visibility: 'Public', status: 'active' },
]

export const SUPPLIERS = [
  { product: 'Beads & accessories', supplier: 'Kantamanto Wholesale', solo_price: 35, group_price: 24, min_orders: 5, status: 'open' },
  { product: 'Fabric (Ankara / Kente)', supplier: 'Opera Market Suppliers', solo_price: 65, group_price: 48, min_orders: 8, status: 'open' },
  { product: 'Packaging materials', supplier: 'ChinaAgent-GH', solo_price: 12, group_price: 8, min_orders: 20, status: 'open' },
]

export const TRANSACTIONS = [
  { user_id: null, type: 'income', description: 'Adire fabric sales (Kantanka orders)', amount: 2400, date: '2026-09-08' },
  { user_id: null, type: 'expense', description: 'Raw material restock: beads & thread', amount: 780, date: '2026-09-05' },
  { user_id: null, type: 'income', description: 'Custom bag commission', amount: 950, date: '2026-09-02' },
  { user_id: null, type: 'expense', description: 'Shop rent (September)', amount: 500, date: '2026-09-01' },
  { user_id: null, type: 'income', description: 'Weekend market stall sales', amount: 1320, date: '2026-08-29' },
  { user_id: null, type: 'expense', description: 'Bolt deliveries (wholesale drops)', amount: 210, date: '2026-08-27' },
]