export const GRANTS = [
  {
    title: 'Tony Elumelu Entrepreneurship Programme',
    amount: 'US$ 5,000 seed capital',
    amount_max: 5000,
    description:
      'Non-refundable seed capital plus business mentorship for African entrepreneurs. The largest entrepreneurship programme on the continent.',
    eligibility: 'African entrepreneur, 18+, with a business idea or early-stage venture. Apply through the TEFConnect portal when applications open.',
    deadline: 'Rolling',
    type: 'All sectors',
    region: 'Pan-Africa',
    source: 'Tony Elumelu Foundation',
    external_url: 'https://tefconnect.com/',
    image_url: null,
  },
  {
    title: 'Google for Startups Accelerator: Africa',
    amount: 'Equity-free support + funding access',
    amount_max: 50000,
    description:
      '10-week accelerator for African tech startups with equity-free support, mentorship, credits and access to Google-invested funding.',
    eligibility: 'Seed to Series-A tech and AI startups with HQ or meaningful operations in Africa.',
    deadline: 'Rolling',
    type: 'Tech / Innovation',
    region: 'Pan-Africa',
    source: 'Google',
    external_url: 'https://startup.google.com/programs/accelerator/africa/',
    image_url: null,
  },
  {
    title: 'Orange Corners',
    amount: 'US$ 5,000 + incubation',
    amount_max: 5000,
    description:
      'Incubation, market access and funding for young entrepreneurs across Africa and the Middle East, including Nigeria and Ghana through local partners.',
    eligibility: 'Young entrepreneurs (18–35) in participating countries, ready for incubation.',
    deadline: 'Rolling',
    type: 'Small business',
    region: 'Pan-Africa',
    source: 'Orange Corners',
    external_url: 'https://www.orangecorners.com/',
    image_url: null,
  },
  {
    title: 'Flat6Labs',
    amount: 'Seed + follow-on funding',
    amount_max: 300000,
    description:
      'One of the region\'s largest seed investors and accelerators, running cohorts with investment, mentoring and founder network.',
    eligibility: 'Early-stage founders with a validated product in MENA and Africa markets.',
    deadline: 'Rolling',
    type: 'Tech / Innovation',
    region: 'Pan-Africa',
    source: 'Flat6Labs',
    external_url: 'https://flat6labs.com/',
    image_url: null,
  },
  {
    title: 'Founders Factory Africa',
    amount: 'Investment + venture studio',
    amount_max: 150000,
    description:
      'Africa-focused venture studio and accelerator investing in tech founders solving real local problems.',
    eligibility: 'Tech founders with a digital product and proof of traction in Africa.',
    deadline: 'Rolling',
    type: 'Tech / Innovation',
    region: 'Pan-Africa',
    source: 'Founders Factory',
    external_url: 'https://foundersfactory.com/',
    image_url: null,
  },
  {
    title: 'Kiva Microloans',
    amount: 'Loans up to US$ 15,000',
    amount_max: 15000,
    description:
      'Crowdfunded, low-interest loans for small businesses in 70+ countries, funded by a community of lenders.',
    eligibility: 'Any business owner. Borrow through a Kiva field partner active in your country.',
    deadline: 'Rolling',
    type: 'Small business',
    region: 'Global',
    source: 'Kiva',
    external_url: 'https://www.kiva.org/',
    image_url: null,
  },
  {
    title: 'Africa No Filter – Story Grants',
    amount: 'US$ 4,000 – 8,000 micro-grants',
    amount_max: 8000,
    description:
      'Micro-grants for African creatives, storytellers and journalists telling nuanced, hopeful narratives about Africa.',
    eligibility: 'African creatives, storytellers and journalists. Calls open periodically for story grants.',
    deadline: 'Rolling',
    type: 'Creative',
    region: 'Pan-Africa',
    source: 'Africa No Filter',
    external_url: 'https://africanofilter.org/',
    image_url: null,
  },
  {
    title: 'GEA YouStart & SME Support (Ghana)',
    amount: 'GH₵ 5,000 – GH₵ 50,000',
    amount_max: 50000,
    description:
      'Government-backed SME support: YouStart starter packages, training and financing windows for young Ghanaian businesses.',
    eligibility: 'Registered Ghanaian MSMEs. YouStart targets entrepreneurs aged 18–40.',
    deadline: 'Rolling',
    type: 'Small business',
    region: 'Ghana',
    source: 'Ghana Enterprises Agency',
    external_url: 'https://gea.gov.gh/',
    image_url: null,
  },
  {
    title: 'Village Capital',
    amount: 'Equity-free investment US$ 50K – 150K',
    amount_max: 150000,
    description:
      'Venture fund investing in early-stage startups; the entrepreneur founders themselves vote on who receives the investment.',
    eligibility: 'Early-stage startups in agriculture, edtech, fintech and climate, per announced programme.',
    deadline: 'Rolling',
    type: 'All sectors',
    region: 'Pan-Africa',
    source: 'Village Capital',
    external_url: 'https://vilcap.com/',
    image_url: null,
  },
  {
    title: 'AFAWA – African Development Bank',
    amount: 'Financing programme',
    amount_max: 250000,
    description:
      'Affirmative Finance Action for Women in Africa: closes the gender financing gap by investing through partner banks in women-led business.',
    eligibility: 'Women-led or women-owned business in an AFAWA partner country, via partner financial institutions.',
    deadline: 'Rolling',
    type: 'Women-led',
    region: 'Pan-Africa',
    source: 'African Development Bank',
    external_url: 'https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/afawa',
    image_url: null,
  },
  {
    title: 'MTN SME Support Programme',
    amount: 'GH₵ 20,000',
    amount_max: 20000,
    description: 'Working-capital support for small businesses, with priority for women-led ventures.',
    eligibility: 'Registered Ghanaian SME. Women-led businesses prioritised. No age limit on founder.',
    deadline: '2026-10-31',
    type: 'Small business',
    region: 'Ghana',
    source: 'MTN Ghana · Innohub Foundation',
    external_url: 'https://www.innohub.com.gh/mtn-sme',
    image_url: null,
  },
  {
    title: 'Absa Young Africa Works Project',
    amount: 'GH₵ 50,000',
    amount_max: 50000,
    description: 'MSME funding programme where 72% of the portfolio goes to women-owned businesses.',
    eligibility: 'Ghanaian MSME with growth potential. Women-owned businesses strongly prioritised.',
    deadline: 'Rolling',
    type: 'Small business',
    region: 'Ghana',
    source: 'Absa Ghana · Mastercard Foundation',
    external_url: 'https://www.absa.com.gh',
    image_url: null,
  },
  {
    title: 'Mastercard Foundation BizBox Programme',
    amount: 'Startup kits + training',
    amount_max: 20000,
    description:
      'In-kind support: business startup kits, training and market access for agri-adjacent businesses via GEA.',
    eligibility:
      'Ghanaian agri-business or agri-adjacent venture. Strong fit for young women-led businesses in agriculture.',
    deadline: '2027-04-30',
    type: 'Agri-business',
    region: 'Ghana',
    source: 'Mastercard Foundation + GEA',
    external_url: 'https://mastercardfdn.org',
    image_url: null,
  },
  {
    title: 'UN Women Empowerment Grant',
    amount: 'Programme-based',
    amount_max: 40000,
    description:
      'Training, mentoring and financial-management skills plus funding for up to 10,000 female entrepreneurs.',
    eligibility:
      'Woman-led venture. Runs through UN Women Africa regional calls for applications.',
    deadline: '2026-11-30',
    type: 'Women-led',
    region: 'Pan-Africa',
    source: 'UN Women · We-Fi',
    external_url: 'https://africa.unwomen.org',
    image_url: null,
  },
  {
    title: 'Meta Business Boost Africa',
    amount: 'US$ 250 + training',
    amount_max: 250,
    description: 'Small ad-budget grants plus digital-skills training for growing SMBs on Meta platforms.',
    eligibility: 'SMB with an active Meta business account, any sector, Africa-based.',
    deadline: 'Rolling',
    type: 'Digital',
    region: 'Pan-Africa',
    source: 'Meta',
    external_url: 'https://about.meta.com',
    image_url: null,
  },
  {
    title: 'Anzisha Prize Fellowship',
    amount: 'US$ up to 40,000 + support',
    amount_max: 40000,
    description:
      "Africa's biggest award for its youngest entrepreneurs: a two-year venture building fellowship with cash stipends, short courses, cloud services and grand prizes, delivered by African Leadership Academy with Mastercard Foundation.",
    eligibility:
      'African national aged 15–22 with an operating venture, founder/leader spending 20+ hours a week on it.',
    deadline: 'Rolling',
    type: 'Youth',
    region: 'Pan-Africa',
    source: 'Anzisha · African Leadership Academy',
    external_url: 'https://anzisha.org/fellowship/',
    image_url: null,
  },
  {
    title: 'AECF Agribusiness Window',
    amount: 'US$ 15,000 – 100,000',
    amount_max: 100000,
    description:
      'African Enterprise Challenge Fund invests in agribusiness and rural enterprises reaching smallholder farmers — grants, repayable grants and investment across 40+ value chains in 23 countries.',
    eligibility:
      'Private-sector company with an innovative agribusiness model in a supported African country, able to match funding in cash or in-kind.',
    deadline: 'Rolling',
    type: 'Agri-business',
    region: 'Sub-Saharan Africa',
    source: 'Africa Enterprise Challenge Fund',
    external_url: 'https://www.aecfafrica.org',
    image_url: null,
  },
  {
    title: 'MEST AI Startup Program',
    amount: 'Fully funded + up to US$ 100,000 pre-seed',
    amount_max: 100000,
    description:
      'A fully-sponsored, in-person incubator in Accra, Ghana: 7 months of AI startup training, a 4-month incubation phase, then a pitch for up to US$ 100,000 in pre-seed investment and entry to the MEST portfolio.',
    eligibility:
      'West/East African national aged 21–35 with software development experience and an entrepreneurial mindset (2027 intake: Ghana, Nigeria, Senegal, Kenya).',
    deadline: 'Rolling',
    type: 'Tech / Innovation',
    region: 'West & East Africa',
    source: 'MEST (Meltwater Entrepreneurial School of Technology)',
    external_url: 'https://meltwater.org/mest-ai-startup-program/',
    image_url: null,
  },
  {
    title: 'USADF Grants to African Enterprises',
    amount: 'US$ up to 250,000',
    amount_max: 250000,
    description:
      'U.S. African Development Foundation provides direct grants, capacity building and convening opportunities to African-owned enterprises and community groups serving underserved, marginalised communities across Africa.',
    eligibility:
      '100%-African-owned and managed, legally recognised African organisation or enterprise; community-led model in an underserved area.',
    deadline: 'Rolling',
    type: 'All sectors',
    region: 'Pan-Africa',
    source: 'U.S. African Development Foundation',
    external_url: 'https://www.usadf.gov/apply',
    image_url: null,
  },
]

export const SAVING_CIRCLES = [
  { name: 'Ayah Susu Circle', amount: 'GH₵ 200 / week', period: 'weekly', total_members: 12, visibility: 'Private', status: 'active' },
  { name: 'Trader Women Group', amount: 'GH₵ 100 / week', period: 'weekly', total_members: 20, visibility: 'Public', status: 'active' },
  { name: 'Market Queens Co-op', amount: 'GH₵ 250 / week', period: 'bi-weekly', total_members: 10, visibility: 'Public', status: 'active' },
  { name: 'Pearl & Gold Traders', amount: 'GH₵ 150 / week', period: 'weekly', total_members: 15, visibility: 'Public', status: 'active' },
]

export const SUPPLIERS = [
  {
    product: 'Beads & accessories',
    supplier: 'Kantamanto Wholesale',
    category: 'Beads',
    unit: 'bag',
    description: 'Assorted glass beads, seed beads and jewellery pins in bulk bags.',
    solo_price: 35,
    group_price: 24,
    min_orders: 5,
    status: 'open',
  },
  {
    product: 'Fabric (Ankara / Kente)',
    supplier: 'Opera Market Suppliers',
    category: 'Fabric',
    unit: 'yard',
    description: 'Premium wax-print ankara and kente textiles at trade prices.',
    solo_price: 65,
    group_price: 48,
    min_orders: 8,
    status: 'open',
  },
  {
    product: 'Packaging materials',
    supplier: 'ChinaAgent-GH',
    category: 'Packaging',
    unit: 'unit',
    description: 'Kraft bags, boxes and branded wrapping for finished products.',
    solo_price: 12,
    group_price: 8,
    min_orders: 20,
    status: 'open',
  },
  {
    product: 'Shea soap base & oils',
    supplier: 'Akyem Soapworks',
    category: 'Cosmetics',
    unit: 'kg',
    description: 'Raw shea butter, coconut oil and soap base for beauty businesses.',
    solo_price: 45,
    group_price: 33,
    min_orders: 10,
    status: 'open',
  },
  {
    product: 'Baking flour (25kg)',
    supplier: 'Makola Agro Foods',
    category: 'Food',
    unit: 'bag',
    description: 'Bulky baking flour and confectionery supplies for bakeries.',
    solo_price: 210,
    group_price: 168,
    min_orders: 12,
    status: 'open',
  },
  {
    product: 'Polythene bags (roll)',
    supplier: 'Kantamanto Products',
    category: 'Packaging',
    unit: 'roll',
    description: 'Crystal polythene rolls for sachet and retail packaging.',
    solo_price: 18,
    group_price: 13,
    min_orders: 15,
    status: 'open',
  },
  {
    product: 'Garment threads (spool box)',
    supplier: 'Opera Textiles',
    category: 'Fabric',
    unit: 'box',
    description: 'Industrial sewing thread spool boxes in common colour sets.',
    solo_price: 55,
    group_price: 41,
    min_orders: 6,
    status: 'open',
  },
  {
    product: 'Sugar & butter (10kg)',
    supplier: 'Makola Agro Foods',
    category: 'Food',
    unit: 'kg',
    description: 'Bulk granulated sugar and baking margarine for food vendors.',
    solo_price: 95,
    group_price: 74,
    min_orders: 9,
    status: 'open',
  },
]

export const TRANSACTIONS = [
  { user_id: null, type: 'income', description: 'Adire fabric sales (Kantanka orders)', amount: 2400, date: '2026-09-08' },
  { user_id: null, type: 'expense', description: 'Raw material restock: beads & thread', amount: 780, date: '2026-09-05' },
  { user_id: null, type: 'income', description: 'Custom bag commission', amount: 950, date: '2026-09-02' },
  { user_id: null, type: 'expense', description: 'Shop rent (September)', amount: 500, date: '2026-09-01' },
  { user_id: null, type: 'income', description: 'Weekend market stall sales', amount: 1320, date: '2026-08-29' },
  { user_id: null, type: 'expense', description: 'Bolt deliveries (wholesale drops)', amount: 210, date: '2026-08-27' },
]